language: node_js
node_js:
  - "8"
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules

install:
  # nothing

jobs:
  include:
    - stage: Test and Build
      script:
      - yarn install --frozen-lockfile --non-interactive
      - yarn test:env
      - yarn test
    - script:
      - docker build -t humanconnection/frontend-nuxt .

after_success:
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag humanconnection/frontend-nuxt humanconnection/frontend-nuxt:alpha
    docker push humanconnection/frontend-nuxt:alpha;
    fi
  - if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag humanconnection/frontend-nuxt humanconnection/frontend-nuxt:edge
    docker push humanconnection/frontend-nuxt:edge;
    fi
