version: '3.5'

services:
  webapp:
    image: humanconnection/frontend-nuxt:edge
    ports:
      - "3000:3000"
    build:
      context: .
      args:
        BUILD_COMMIT: ${BUILD_COMMIT}
    networks:
      - hc-network
    environment:
      - WEBAPP_HOST=webapp
      - WEBAPP_BASE_URL=http://localhost:3000
      - API_HOST=api.127.0.0.1.xip.io
      - WEBAPP_PORT=3000
      - API_PORT=3030
      - MAPBOX_TOKEN=pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ

networks:
  hc-network:
    name: hc-network
